### ISSUE TITLE
Upload .jar file

### ISSUE THREAD

**Issue by MisterBernd** [Tobiplayer3/LimitedPlaytime#11]
Hi, I wanted to ask if the plugin is fully working.
If it is, could you compile it and upload it to the versions section?

**Comment by Tobiplayer3** [comment]
Hey, I'm sorry but the plugin is not fully functioning yet. I haven't had too much interest in Minecraft recently, so development was really slow. I still have some uncommited changes but they don't work right now, either.
The main things missing are commands, output messages and some refinements for the config, whenever I finish those I'll definitely upload a compiled version.

**Comment by MisterBernd** [comment]
Okay, thank you for your quick response!
